[project]
name = "econstor-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "pydantic>=2.10.6",
    "requests>=2.32.4",
]
